openapi: 3.0.3
info:
  title: Analytics Service API
  version: "1.0.0"
  description: |
    Consumes all Kafka events and stores analytics data.
    Exposes read-only analytics dashboards.
servers:
  - url: http://localhost:4700
  - url: https://analytics.api.example.com

tags:
  - name: analytics

components:
  schemas:
    SalesStats:
      type: object
      properties:
        totalOrders: { type: integer }
        totalRevenue: { type: number }
        date: { type: string }

    PopularItem:
      type: object
      properties:
        productId: { type: string }
        count: { type: integer }

paths:
  /analytics/sales/daily:
    get:
      tags: [analytics]
      summary: Daily aggregated sales stats
      parameters:
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Daily analytics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SalesStats"

  /analytics/products/popular:
    get:
      tags: [analytics]
      summary: Most frequently purchased products
      responses:
        "200":
          description: Popular products
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/PopularItem" }
