openapi: 3.0.3
info:
  title: Product Service API
  version: "1.0.0"
  description: |
    Handles product catalog, pricing, and stock management.
servers:
  - url: http://localhost:4300
  - url: https://products.api.example.com

tags:
  - name: products
    description: Query products
  - name: admin
    description: Admin/product management

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    Product:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        price: { type: number }
        stock: { type: integer }
        description: { type: string }
        imageUrl: { type: string }
    CreateProductRequest:
      type: object
      required: [name, price, stock]
      properties:
        name: { type: string }
        price: { type: number }
        stock: { type: integer }
        description: { type: string }
        imageUrl: { type: string }
    UpdateStockRequest:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              productId: { type: string }
              qty: { type: integer }

paths:
  /products:
    get:
      tags: [products]
      summary: List products
      responses:
        "200":
          description: Product list
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/Product" }

    post:
      tags: [admin]
      summary: Create product
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/CreateProductRequest" }
      responses:
        "201": { description: Created }

  /products/{productId}:
    get:
      tags: [products]
      summary: Get product
      parameters:
        - in: path
          name: productId
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Product
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Product" }
        "404": { description: Not found }

  /products/stock/reserve:
    post:
      tags: [admin]
      summary: Reserve stock for an order
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/UpdateStockRequest" }
      responses:
        "200": { description: Reserved }
      x-events:
        publishes:
          - topic: product.stock.reserved

  /products/stock/release:
    post:
      tags: [admin]
      summary: Release previously reserved stock
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/UpdateStockRequest" }
      responses:
        "200": { description: Released }
      x-events:
        publishes:
          - topic: product.stock.released
