apiVersion: v1
kind: Secret
metadata:
  name: analytics-db-secret
  namespace: dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: analytics_db
  MYSQL_USER: analytics_user
  MYSQL_PASSWORD: analytics_password
