apiVersion: v1
kind: ConfigMap
metadata:
  name: service-common-config
  namespace: dev
  labels:
    project: food-delivery-distributed-system
data:
  NODE_ENV: "development"
  RABBITMQ_URL: "amqp://admin:admin123@rabbitmq.dev.svc.cluster.local:5672"
