apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: dev
type: Opaque
data:
  # Base64 encoded values
  # MYSQL_USER: order_service
  MYSQL_USER: b3JkZXJfc2VydmljZQ==
  # MYSQL_PASSWORD: order_password_123
  MYSQL_PASSWORD: b3JkZXJfcGFzc3dvcmRfMTIz
  # MYSQL_ROOT_PASSWORD: root_password_123
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZF8xMjM=
