apiVersion: v1
kind: Secret
metadata:
  name: product-db-secret
  namespace: dev
type: Opaque
stringData:
  MYSQL_USER: product_service
  MYSQL_PASSWORD: product_password_123
  MYSQL_ROOT_PASSWORD: root_password_123
