apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: yegeta100/user-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: service-common-config
                  key: NODE_ENV

            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: service-common-config
                  key: RABBITMQ_URL

            - name: MYSQL_HOST
              value: "user-db.dev.svc.cluster.local"

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_PASSWORD

            - name: MYSQL_DATABASE
              value: "user_db"

            - name: DATABASE_URL
              value: "mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@$(MYSQL_HOST):3306/$(MYSQL_DATABASE)"

          imagePullPolicy: IfNotPresent # Use "Always" if you want to always pull the latest image
