apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: app-serviceaccount
      containers:
        - name: user-service
          image: your-dockerhub/user-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE_NAME
              value: user-service
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: user-db.dev.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: user_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_PASSWORD
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: service-common-config
                  key: RABBITMQ_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
