apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: user_db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          imagePullPolicy: IfNotPresent
      volumes:
        - name: mysql-data
          hostPath:
            path: /tmp/k3d-mysql-data
            type: DirectoryOrCreate
