apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: dev
type: Opaque
stringData:
  MYSQL_USER: user_service
  MYSQL_PASSWORD: user_password_123
  MYSQL_ROOT_PASSWORD: root_password_123
