apiVersion: v1
kind: Secret
metadata:
  name: delivery-db-secret
  namespace: dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: delivery_db
  MYSQL_USER: delivery_user
  MYSQL_PASSWORD: delivery_password
